// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAodR_EFydwv7IJKD9XAmZrkPC6DBoj6aY',
    appId: '1:1041661690592:web:9a55288dfd47afe023c685',
    messagingSenderId: '1041661690592',
    projectId: 'atw-task-a2b57',
    authDomain: 'atw-task-a2b57.firebaseapp.com',
    storageBucket: 'atw-task-a2b57.firebasestorage.app',
    measurementId: 'G-NZCQGPM4VQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCT3erVRczgzgiDQmXj1MGCsvU-7XNBu1Y',
    appId: '1:1041661690592:android:47a523e3d77b507423c685',
    messagingSenderId: '1041661690592',
    projectId: 'atw-task-a2b57',
    storageBucket: 'atw-task-a2b57.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcpT_3ItuteFKH1zxwp5OydUnk6ct-Rxg',
    appId: '1:1041661690592:ios:86b8ad8dd344df9c23c685',
    messagingSenderId: '1041661690592',
    projectId: 'atw-task-a2b57',
    storageBucket: 'atw-task-a2b57.firebasestorage.app',
    iosBundleId: 'com.example.atwTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcpT_3ItuteFKH1zxwp5OydUnk6ct-Rxg',
    appId: '1:1041661690592:ios:86b8ad8dd344df9c23c685',
    messagingSenderId: '1041661690592',
    projectId: 'atw-task-a2b57',
    storageBucket: 'atw-task-a2b57.firebasestorage.app',
    iosBundleId: 'com.example.atwTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAodR_EFydwv7IJKD9XAmZrkPC6DBoj6aY',
    appId: '1:1041661690592:web:2e28e8a0133fd19323c685',
    messagingSenderId: '1041661690592',
    projectId: 'atw-task-a2b57',
    authDomain: 'atw-task-a2b57.firebaseapp.com',
    storageBucket: 'atw-task-a2b57.firebasestorage.app',
    measurementId: 'G-X9ECPJB8HD',
  );

}